### ISSUE TITLE
请注明编译环境依赖

### ISSUE THREAD

**Issue by zhaoxitao** [DCZYewen/Python-Silk-Module#10]
由于平台架构原因无法直接使用 wheel 安装所以需要手工编译，但是编译过程中提示各种文件缺失，目前看起来涉及到 ffmpeg, libavcodec等，但是目前依旧报错不断，请能都标明编译所需的依赖，感谢。

**Comment by wyapx** [comment]
请提供编译时产生的报错，还有编译环境信息，谢谢

**Comment by zhaoxitao** [comment]
Hi 感谢答复，目前我已经编译成功，但是调用时会报错。具体信息如下，还请指导：
平台：
ARM 32位（树莓派4B）

环境：
Python 3.9.2

调用报错日志：
` $ python3 -m pysilk target.wav output.silk`

```
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 188, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.9/runpy.py", line 147, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.9/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/home/pi/.local/lib/python3.9/site-packages/pysilk/__init__.py", line 1, in <module>
    from .pysilk import encode, encode_file, decode, decode_file
  File "/home/pi/.local/lib/python3.9/site-packages/pysilk/pysilk.py", line 14, in <module>
    from .coder import silkEncode, silkDecode
ImportError: /home/pi/.local/lib/python3.9/site-packages/pysilk/coder.cpython-39-arm-linux-gnueabihf.so: undefined symbol: SKP_Silk_resampler_up2


```

问题定位：
编译目录下查找SKP_Silk_resampler_up2.o文件是有的，但是ldd -r 无法找到

**Comment by DCZYewen** [comment]
请提供本地的编译器版本信息，另请尝试使用crosstools交叉编译
另：你之前的尝试中不可编译，经过何种使得操作编译成功通过
程序本身对于Skype的silk codec库已经移除了大多数不可移植的asm以及平台相关代码

**Comment by zhaoxitao** [comment]
编译器版本：
` $ gcc --version
gcc (Debian 10.2.1-6) 10.2.1 20210110
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
`
之前编译最后是如何成功的，因为经过了太多次尝试，我没有记录下来所有的步骤，但是大致的思路就是每当出现一个报错的时候，就去找对应的依赖，安装好依赖后再继续尝试，多次尝试解决完所有的依赖以后，就成功编译了。（前提是我已经通过 pip 安装了本源里要求的 requirments.txt 依赖。

**Comment by DCZYewen** [comment]
对不起  我在x86 Debian10中使用gcc 10并未复现你的问题。再次建议你使用crosstools交叉编译
